import {
  Zap,
  Target,
  Trophy,
  Dumbbell,
  Waves,
  Mountain,
  Flame,
  Bike,
  Activity,
  Award,
  CircleDot,
  Snowflake,
  Wind,
  Music,
} from "lucide-react";

export const SPORTS_ICONS: Record<string, any> = {
  "FOOTBALL": Target,
  "TENNIS": CircleDot,
  "TENNIS DE TABLE": CircleDot,
  "BASKET-BALL": Trophy,
  "VOLLEY-BALL": Trophy,
  "VÉLO": Bike,
  "VTT": Bike,
  "RUNNING": Zap,
  "ATHLÉTISME": Zap,
  "SKI": Snowflake,
  "SNOWBOARD": Wind,
  "MUSCULATION": Dumbbell,
  "FITNESS": Dumbbell,
  "CROSSFIT": Dumbbell,
  "NATATION": Waves,
  "YOGA": Activity,
  "PILATES": Activity,
  "GOLF": Target,
  "BOXE": Flame,
  "ARTS MARTIAUX": Flame,
  "ESCALADE": Mountain,
  "RANDONNÉE": Mountain,
  "SURF": Waves,
  "RUGBY": Target,
  "PADEL": CircleDot,
  "EQUITATION": Mountain,
  "ÉQUITATION": Mountain,
  "SKATEBOARD": Zap,
  "HOCKEY": Target,
  "AVIRON": Waves,
  "DANCE": Music,
  "PATINAGE": Snowflake,
  "POLO": Target,
  "ROLLER": Zap,
  "SPORTS DE PLEIN AIR": Mountain,
  "SPORTS DE RAQUETTE": CircleDot,
  "SPORTS NAUTIQUES": Waves,
  "TIR À L'ARC": Target,
  "VOILE": Wind,
  "WATER-POLO": Waves,
  "CANOË-KAYAK": Waves,
  "PLONGÉE": Waves,
};

export const HANDEDNESS_SPORTS = [
  "TENNIS",
  "GOLF",
  "BOXE",
  "PADEL",
  "HOCKEY",
  "RUGBY",
  "TENNIS DE TABLE",
];

export const STANCE_SPORTS = ["SNOWBOARD", "SURF", "SKATEBOARD", "SKI"];

export const LEVEL_DEFINITIONS = [
  {
    id: "BEGINNER",
    label: "Novice",
    desc: "Découverte, apprentissage des bases, pratique de loisir ou d'initiation.",
    glow: "hover:shadow-[0_0_20px_rgba(161,161,170,0.05)]",
    activeGlow: "shadow-[0_0_30px_rgba(161,161,170,0.15)] border-zinc-400 bg-zinc-400/5 text-zinc-300",
  },
  {
    id: "INTERMEDIATE",
    label: "Intermédiaire",
    desc: "Pratique régulière, autonomie technique, recherche de progression.",
    glow: "hover:shadow-[0_0_20px_rgba(129,140,248,0.05)]",
    activeGlow: "shadow-[0_0_30px_rgba(129,140,248,0.15)] border-indigo-500 bg-indigo-500/10 text-indigo-400",
  },
  {
    id: "ADVANCED",
    label: "Confirmé",
    desc: "Technique maîtrisée, pratique intensive, matériel précis et performant.",
    glow: "hover:shadow-[0_0_20px_rgba(245,158,11,0.05)]",
    activeGlow: "shadow-[0_0_30px_rgba(245,158,11,0.15)] border-amber-500 bg-amber-500/10 text-amber-500",
  },
  {
    id: "PRO",
    label: "Pro",
    desc: "Compétition nationale/internationale, exigences maximales, niveau athlète.",
    glow: "hover:shadow-[0_0_20px_rgba(244,63,94,0.05)]",
    activeGlow: "shadow-[0_0_30px_rgba(244,63,94,0.15)] border-rose-500 bg-rose-500/5 text-rose-500",
  },
];
